{
  "formatVersion": "1.1",
  "component": {
    "group": "so.openhorizon",
    "module": "sapient",
    "version": "0.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sapient-0.6.5.aar",
          "url": "sapient-0.6.5.aar",
          "size": 6293585,
          "sha512": "0c676f256c0a3d1d3b22d945663d4e3e587c2e1c3522e7fa8b790c40eaa4b4be553ef3145bc54c87ea7d3ccb3678c91d11e54b63d696040e4224db93de9c080b",
          "sha256": "270e299aec6a4e6f7fa1a37ba57abeea19a5b161f72d8373f0ddc1dcf328cd6b",
          "sha1": "94ccafd3bbdf5a9aa11b7d93df6ec651789a17eb",
          "md5": "5f50c3268348f05b0d6b2c641e960a3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sapient-0.6.5.aar",
          "url": "sapient-0.6.5.aar",
          "size": 6293585,
          "sha512": "0c676f256c0a3d1d3b22d945663d4e3e587c2e1c3522e7fa8b790c40eaa4b4be553ef3145bc54c87ea7d3ccb3678c91d11e54b63d696040e4224db93de9c080b",
          "sha256": "270e299aec6a4e6f7fa1a37ba57abeea19a5b161f72d8373f0ddc1dcf328cd6b",
          "sha1": "94ccafd3bbdf5a9aa11b7d93df6ec651789a17eb",
          "md5": "5f50c3268348f05b0d6b2c641e960a3b"
        }
      ]
    }
  ]
}
