{
  "formatVersion": "1.1",
  "component": {
    "group": "so.openhorizon",
    "module": "sapient",
    "version": "0.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sapient-0.6.4.aar",
          "url": "sapient-0.6.4.aar",
          "size": 6273584,
          "sha512": "e3ba2b2321fb91178787342a847f8b256be6f93ef8dc8dfe4ec7ff2d0752d6a8e0ba9bcc14bb7b859428816923eb807dd4bf7cf66e67170194e5edd6f45cfc51",
          "sha256": "f5738adb7d78b10b3d6df905ba0ca08ef9bc6d3bc91908215a069862f0dcf062",
          "sha1": "3f4f0fe99e72771fb062279014cf472078206a1c",
          "md5": "46bb5aa766c2fc4c12b93174a0935f4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sapient-0.6.4.aar",
          "url": "sapient-0.6.4.aar",
          "size": 6273584,
          "sha512": "e3ba2b2321fb91178787342a847f8b256be6f93ef8dc8dfe4ec7ff2d0752d6a8e0ba9bcc14bb7b859428816923eb807dd4bf7cf66e67170194e5edd6f45cfc51",
          "sha256": "f5738adb7d78b10b3d6df905ba0ca08ef9bc6d3bc91908215a069862f0dcf062",
          "sha1": "3f4f0fe99e72771fb062279014cf472078206a1c",
          "md5": "46bb5aa766c2fc4c12b93174a0935f4e"
        }
      ]
    }
  ]
}
