{
  "formatVersion": "1.1",
  "component": {
    "group": "so.openhorizon",
    "module": "sapient",
    "version": "0.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sapient-0.6.4.aar",
          "url": "sapient-0.6.4.aar",
          "size": 6277682,
          "sha512": "4f19df95dc01ca27dea039c4e4771654e943905f9e3d5e3369b0d0090cc8a53c6d4dd6384772ac029cb11a9e932a049c64171879a5047f94512c6c582cc7e309",
          "sha256": "efe6f93e00ae0bdade62dd0d6c9a1115b6e1cadee06e5bfb86761fa1f8cf0ab7",
          "sha1": "a3ccf11e8fea2deca407a2491335f9b2ed4be3f1",
          "md5": "f620642c3aa6e516a2326cad5a183295"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sapient-0.6.4.aar",
          "url": "sapient-0.6.4.aar",
          "size": 6277682,
          "sha512": "4f19df95dc01ca27dea039c4e4771654e943905f9e3d5e3369b0d0090cc8a53c6d4dd6384772ac029cb11a9e932a049c64171879a5047f94512c6c582cc7e309",
          "sha256": "efe6f93e00ae0bdade62dd0d6c9a1115b6e1cadee06e5bfb86761fa1f8cf0ab7",
          "sha1": "a3ccf11e8fea2deca407a2491335f9b2ed4be3f1",
          "md5": "f620642c3aa6e516a2326cad5a183295"
        }
      ]
    }
  ]
}
