{
  "formatVersion": "1.1",
  "component": {
    "group": "so.openhorizon",
    "module": "sapient",
    "version": "0.6.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sapient-0.6.4.aar",
          "url": "sapient-0.6.4.aar",
          "size": 6273583,
          "sha512": "60523a89dd1c49b6b0a26a1fa30021baaeb9daa1b8d728e52fc62b4d177059b883a14d460f0d8cb9acd8954043eb531254aa4198e91bbc9cf663493d8346a1f2",
          "sha256": "555464a1de8c6918f06982e992eade62a58da6ca59c5c6702aa27cc6861c7660",
          "sha1": "c812754d6ab85dfe3dd1ed1f43fa49f09cc1b8c7",
          "md5": "da8903c92181da58389d364dd60ced1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sapient-0.6.4.aar",
          "url": "sapient-0.6.4.aar",
          "size": 6273583,
          "sha512": "60523a89dd1c49b6b0a26a1fa30021baaeb9daa1b8d728e52fc62b4d177059b883a14d460f0d8cb9acd8954043eb531254aa4198e91bbc9cf663493d8346a1f2",
          "sha256": "555464a1de8c6918f06982e992eade62a58da6ca59c5c6702aa27cc6861c7660",
          "sha1": "c812754d6ab85dfe3dd1ed1f43fa49f09cc1b8c7",
          "md5": "da8903c92181da58389d364dd60ced1c"
        }
      ]
    }
  ]
}
