{
  "formatVersion": "1.1",
  "component": {
    "group": "so.openhorizon",
    "module": "sapient",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sapient-0.6.0.aar",
          "url": "sapient-0.6.0.aar",
          "size": 6049852,
          "sha512": "c088ace62852178b328a671bb1a03d0f64b4dd72777e933e888cc1c5e76c5201ef821c7b8c48f6a967cb22febc3a71985d7f53ba35da12d1ee5b5f5f12575b2d",
          "sha256": "bf5a60cbf874da87ea75446947a71eb77ff107b8c5f1e54558fc3e6303805263",
          "sha1": "42f32a7f1d91bddc767f383803e051fd53e15676",
          "md5": "92c6d4faa32def53d7d299292aec7d05"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.14.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jna",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sapient-0.6.0.aar",
          "url": "sapient-0.6.0.aar",
          "size": 6049852,
          "sha512": "c088ace62852178b328a671bb1a03d0f64b4dd72777e933e888cc1c5e76c5201ef821c7b8c48f6a967cb22febc3a71985d7f53ba35da12d1ee5b5f5f12575b2d",
          "sha256": "bf5a60cbf874da87ea75446947a71eb77ff107b8c5f1e54558fc3e6303805263",
          "sha1": "42f32a7f1d91bddc767f383803e051fd53e15676",
          "md5": "92c6d4faa32def53d7d299292aec7d05"
        }
      ]
    }
  ]
}
